/*
 * ChangePasswordDialog.java
 *
 * Created on 16. März 2007, 16:35
 */

package org.jcoderz.keytoolz.keystoreexplorer;

import java.util.Arrays;

import javax.swing.JOptionPane;

/**
 * @author cloroff
 */
public class ChangePasswordDialog
    extends javax.swing.JDialog
{

  private static final long serialVersionUID = 1L;


  /** Creates new form ChangePasswordDialog */
  public ChangePasswordDialog(java.awt.Frame parent, boolean modal)
  {
    super(parent, modal);
    initComponents();
  }


  /**
   * This method is called from within the constructor to initialize the
   * form. WARNING: Do NOT modify this code. The content of this method
   * is always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc=" Generated Code ">
  //GEN-BEGIN:initComponents
  private void initComponents()
  {
    jPasswordField1 = new javax.swing.JPasswordField();
    jPasswordField2 = new javax.swing.JPasswordField();
    jPasswordField3 = new javax.swing.JPasswordField();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Change password");

    jLabel1.setFont(new java.awt.Font("Dialog", 0, 12));
    jLabel1.setText("current password:");

    jLabel2.setFont(new java.awt.Font("Dialog", 0, 12));
    jLabel2.setText("new password:");

    jLabel3.setFont(new java.awt.Font("Dialog", 0, 12));
    jLabel3.setText("retype new password:");

    jButton1.setText("OK");
    jButton1.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        jButton1ActionPerformed(evt);
      }
    });

    jButton2.setText("Cancel");
    jButton2.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        jButton2ActionPerformed(evt);
      }
    });

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
        .add(
            layout.createSequentialGroup().addContainerGap().add(
                layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
                    layout.createSequentialGroup().add(jLabel1).add(22, 22, 22)).add(jLabel2).add(
                    jLabel3)).addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(
                layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false).add(
                    jPasswordField2).add(jPasswordField1).add(jPasswordField3,
                    org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .add(
            layout.createSequentialGroup().add(37, 37, 37).add(jButton1).addPreferredGap(
                org.jdesktop.layout.LayoutStyle.RELATED, 78, Short.MAX_VALUE).add(jButton2).add(40,
                40, 40)));
    layout.setVerticalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
        .add(
            layout.createSequentialGroup().addContainerGap().add(
                layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE).add(jLabel1)
                    .add(jPasswordField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)).addPreferredGap(
                org.jdesktop.layout.LayoutStyle.RELATED).add(
                layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE).add(
                    jPasswordField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                    org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                    org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).add(jLabel2)).addPreferredGap(
                org.jdesktop.layout.LayoutStyle.RELATED).add(
                layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE).add(jLabel3)
                    .add(jPasswordField3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)).add(14, 14, 14).add(
                layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE).add(jButton1)
                    .add(jButton2)).addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                Short.MAX_VALUE)));
    pack();
  }// </editor-fold>//GEN-END:initComponents


  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)
  {// GEN-FIRST:event_jButton2ActionPerformed
    setVisible(false);
  }// GEN-LAST:event_jButton2ActionPerformed


  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)
  {// GEN-FIRST:event_jButton1ActionPerformed
    if (Arrays.equals(jPasswordField2.getPassword(), jPasswordField3.getPassword()))
    {
      setVisible(false);
    }
    else
    {
      JOptionPane.showMessageDialog(this, "The new passwords are different.", "Password error",
          JOptionPane.ERROR_MESSAGE);
      jPasswordField2.setText("");
      jPasswordField3.setText("");
    }
  }// GEN-LAST:event_jButton1ActionPerformed


  public char[] getOldPassword()
  {
    return jPasswordField1.getPassword();
  }


  public char[] getNewPassword()
  {
    return jPasswordField2.getPassword();
  }


  /**
   * @param args the command line arguments
   */
  public static void main(String args[])
  {
    java.awt.EventQueue.invokeLater(new Runnable()
    {
      public void run()
      {
        new ChangePasswordDialog(new javax.swing.JFrame(), true).setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JPasswordField jPasswordField1;
  private javax.swing.JPasswordField jPasswordField2;
  private javax.swing.JPasswordField jPasswordField3;
  // End of variables declaration//GEN-END:variables

}
