/*
 * PasswordDialog.java
 *
 * Created on __DATE__, __TIME__
 */

package org.jcoderz.keytoolz.keystoreexplorer;

/**
 * @author __USER__
 */
public class PasswordDialog
    extends javax.swing.JDialog
{
  private static final long serialVersionUID = 1L;
  private static final String labelText = " password";


  /** Creates new form PasswordDialog */
  public PasswordDialog(java.awt.Frame parent, String passwordType, boolean modal)
  {
    super(parent, modal);
    initComponents();
    jLabel1.setText(passwordType + labelText);
  }


  /**
   * This method is called from within the constructor to initialize the
   * form. WARNING: Do NOT modify this code. The content of this method
   * is always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc=" Generated Code
  // ">//GEN-BEGIN:initComponents
  private void initComponents()
  {
    jPasswordField1 = new javax.swing.JPasswordField();
    jLabel1 = new javax.swing.JLabel();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Enter Password");
    setLocationByPlatform(true);
    jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter()
    {
      public void keyTyped(java.awt.event.KeyEvent evt)
      {
        PasswordDialog.this.keyTyped(evt);
      }
    });

    jLabel1.setFont(new java.awt.Font("Arial", 1, 14));
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

    jButton1.setText("OK");
    jButton1.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        okActionPerformed(evt);
      }
    });

    jButton2.setText("Cancel");
    jButton2.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        cancelActionPerformed(evt);
      }
    });

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
        .add(
            layout.createSequentialGroup().addContainerGap().add(
                layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(
                        org.jdesktop.layout.GroupLayout.TRAILING,
                        layout.createSequentialGroup().add(jButton1).addPreferredGap(
                            org.jdesktop.layout.LayoutStyle.RELATED, 29, Short.MAX_VALUE).add(
                            jButton2)).add(jPasswordField1,
                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE).add(
                        org.jdesktop.layout.GroupLayout.TRAILING, jLabel1,
                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                .addContainerGap()));
    layout.setVerticalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
        .add(
            layout.createSequentialGroup().addContainerGap().add(jLabel1,
                org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 38,
                org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).addPreferredGap(
                org.jdesktop.layout.LayoutStyle.RELATED).add(jPasswordField1,
                org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).add(20, 20, 20).add(
                layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE).add(jButton2)
                    .add(jButton1)).addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                Short.MAX_VALUE)));
    pack();
  }// </editor-fold>//GEN-END:initComponents


  // GEN-FIRST:event_keyTyped
  private void keyTyped(java.awt.event.KeyEvent evt)
  {
    if (evt.getKeyChar() == java.awt.event.KeyEvent.VK_ENTER)
    {
      this.setVisible(false);
    }
  }// GEN-LAST:event_keyTyped


  // GEN-FIRST:event_cancelActionPerformed
  private void cancelActionPerformed(java.awt.event.ActionEvent evt)
  {
    this.jPasswordField1.setText(null);
    this.setVisible(false);
  }// GEN-LAST:event_cancelActionPerformed


  // GEN-FIRST:event_okActionPerformed
  private void okActionPerformed(java.awt.event.ActionEvent evt)
  {
    this.setVisible(false);
  }// GEN-LAST:event_okActionPerformed


  /**
   * @param args the command line arguments
   */
  public static void main(String args[])
  {
    java.awt.EventQueue.invokeLater(new Runnable()
    {
      public void run()
      {
        new PasswordDialog(new javax.swing.JFrame(), "Test", true).setVisible(true);
      }
    });
  }


  public char[] getPassword()
  {
    return jPasswordField1.getPassword();
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPasswordField jPasswordField1;
  // End of variables declaration//GEN-END:variables
}
